apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: monitoring
spec:
  type: ExternalName
  externalName: monitoring-service-ext
  selector:
    app: monitoring
  ports:
    - name: prometheus
      protocol: TCP
      port: 30003
      targetPort: 9090