{
 "title": "Main",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Database logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"database-ns\", container=\"mariadb\"} |= ``"
    }
   ]
  },
  {
   "title": "MariaDB instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_up{job=\"mariadb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebApp status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"webapp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "redis_up{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}