apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.2
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: secret
      - name: phpmyadmin
        image: phpmyadmin:5
        ports:
        - containerPort: 80 
        env:
        - name: PMA_HOST
          value: localhost
        - name: PMA_PORT
          value: "3306"
