---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: database-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.2
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: secret
        volumeMounts:
        - name: db-init
          mountPath: "/docker-entrypoint-initdb.d"
        - name: db-data
          mountPath: "/var/lib/mysql"
      - name: phpmyadmin
        image: phpmyadmin:5
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: "127.0.0.1"
      initContainers:
        - name: mysql-exporter
          image: prom/mysqld-exporter
          restartPolicy: Always
          args:
            - "--config.my-cnf=/cfg/config.my-cnf"
          ports:
            - containerPort: 9104
          volumeMounts:
            - mountPath: "/cfg"
              name: mysql-exporter-config
      volumes:
      - name: db-init
        configMap:
          name: db-configmap
          items:
            - key: init.sql
              path: init.sql
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data-pvc
      - name: mysql-exporter-config
        configMap:
          name: db-configmap
          items:
            - key: mysql-exporter.my-cnf
              path: config.my-cnf
