apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.2
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: secret
        volumeMounts:
        - name: init
          mountPath: "/docker-entrypoint-initdb.d/init.sql"
      - name: phpmyadmin
        image: phpmyadmin:5
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: "127.0.0.1"
    volumes:
    - name: init
      configMap:
        name: db-configmap
        items:
        - key: "init-path"
