apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: mariadb
  ports:
    - name: phpmyadmin
      protocol: TCP
      port: 30001
      targetPort: 80
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306