apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: ingress-ns
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - local
    secretName: self-signed
  rules:
    - host: web.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp-service-ext
                port:
                  number: 30000
    - host: phpmyadmin.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: database-service-ext
                port:
                  number: 30001
    - host: redis.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cache-service-ext
                port:
                  number: 30002
    - host: prometheus.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-service-ext
                port:
                  number: 30003
    - host: grafana.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-service-ext
                port:
                  number: 30004
    - host: alertmanager.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-service-ext
                port:
                  number: 30005
                  
