apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #nginx.ingress.kubernetes.io/server-snippets: |
    #  location / {
    #    return 302 /phpmyadmin;
    #  }
    #nginx.org/location-snippets: |
    #  add_header my-test-header test-value;
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /web
            pathType: Prefix
            backend:
              service:
                name: webapp-service
                port:
                  number: 30000
          - path: /phpmyadmin
            pathType: Prefix
            backend:
              service:
                name: database-service
                port:
                  number: 30001
                  
