---
apiVersion: v1
kind: Service
metadata:
  name: webapp-green-service
  namespace: webapp-ns
spec:
  selector:
    app: webapp
    color: green
  ports:
    - name: webapp
      protocol: TCP
      port: 30006
      targetPort: 80
    - name: blackbox-exporter
      protocol: TCP
      port: 9115
      targetPort: 9115