---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/home/node/app/src/img/"
            name: shared-volume
        env:
        - name: INSTANCIA
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DB_HOST
          value: database-service.database-ns.svc.cluster.local
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-user
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-user
              key: password
        - name: REDIS_HOST
          value: cache-service.cache-ns.svc.cluster.local
      # initContainers:
      #   - name: blackbox-exporter
      #     image: quay.io/prometheus/blackbox-exporter
      #     restartPolicy: Always
      #     args:
      #       - "--config.file=/config/config.yml"
      #     ports:
      #       - containerPort: 9115
      #     volumeMounts:
      #       - mountPath: "/config"
      #         name: blackbox-config
      volumes:
        - name: shared-volume
          hostPath:
            path: /shared
            type: Directory
        # - name: blackbox-config
        #   configMap:
        #     name: blackbox-configmap
        #     items:
        #       - key: blackbox-config.yml
        #         path: config.yml
