---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-ns
spec:
  selector:
    app: webapp
    color: blue
  ports:
    - name: webapp
      protocol: TCP
      port: 30000
      targetPort: 80
    - name: blackbox-exporter
      protocol: TCP
      port: 9115
      targetPort: 9115