apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: database-service
        - name: DB_USER
          value: secret
        - name: DB_PASS
          value: secret
        - name: REDIS_HOST
          value: cache-service
