apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-ns
spec:
  selector:
    app: webapp
  ports:
    - name: webapp
      protocol: TCP
      port: 30000
      targetPort: 80