apiVersion: 1
groups:
  - orgId: 1
    name: Database
    folder: Log-alerts
    interval: 1m
    rules:
      - uid: ae6r5bbgqbg1se
        title: Database warnings
        condition: C
        data:
          - refId: A
            queryType: range
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: P8E80F9AEF21F6940
            model:
              datasource:
                type: loki
                uid: P8E80F9AEF21F6940
              editorMode: code
              expr: sum by (message)(count_over_time({container="mariadb"} |= `[Warning]`| pattern "<_> <message> duration<_>" [10m]))
              intervalMs: 1000
              maxDataPoints: 43200
              queryType: range
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        isPaused: false
        notification_settings:
          receiver: grafana-default-email
