name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#  lint-format:
#    runs-on: ubuntu-latest
#    name: Format files
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: "20"
#      - name: npm install
#        run: npm ci

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Jest
        run: npm test

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
        # Lint y format del código
      - name: lint and format
        run: npm run format
        # Push de los cambios en el código
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          commit_message: "GitHub Actions: formated, linted and tests passed"

  deploy-echo:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Para integrar la nueva versión en k8s deberías ejecutar los siguientes comandos:"
      - run: echo "cd WebApp"
      - run: echo "minikube image rm webapp:latest"
      - run: echo "minikube image build -t webapp:latest ."
      - run: echo "cd ../k8s"
      - run: echo "kubectl delete -n webapp-ns deployment webapp-deployment"
      - run: echo "kubectl apply -f ./webapp/web-deployment"